[package]
name = "word_filter"
version = "0.3.0"
authors = ["Anders Evensen"]
edition = "2018"
description = "A Word Filter for filtering text."
readme = "README.md"
repository = "https://github.com/Anders429/word_filter"
license = "MIT OR Apache-2.0"
categories = ["data-structures", "game-development", "no-std", "text-processing", "value-formatting"]
keywords = ["wordfilter", "word", "filter", "censor", "string"]
exclude = [".github/*", "clippy.toml"]

[dependencies]
by_address = "1.0.4"
hashbrown = "0.9.1"
nested_containment_list = "0.3.0"
str_overlap = "0.4.3"

[dev-dependencies]
claim = "0.5.0"
