[package]
name = "word_filter"
version = "0.1.0"
authors = ["Anders Evensen"]
edition = "2018"
description = "A robust implementation of a Word Filter."
license = "MIT OR Apache-2.0"
categories = ["data-structures", "game-development", "text-processing", "value-formatting"]
readme = "README.md"
repository = "https://github.com/Anders429/word_filter"
exclude = [".github/*"]

[dependencies]
nested_containment_list = "0.1.0"
str_overlap = "0.1.1"
