[package]
name = "word_filter"
version = "0.1.6"
authors = ["Anders Evensen"]
edition = "2018"
description = "A robust implementation of a Word Filter."
readme = "README.md"
repository = "https://github.com/Anders429/word_filter"
license = "MIT OR Apache-2.0"
categories = ["data-structures", "game-development", "no-std", "text-processing", "value-formatting"]
keywords = ["wordfilter", "word", "filter", "censor", "string"]
exclude = [".github/*"]

[dependencies]
by_address = "1.0.4"
hashbrown = "0.9.1"
nested_containment_list = "0.1.1"
str_overlap = "0.4.2"

[build-dependencies]
autocfg = "1.0.1"

[dev-dependencies]
claim = "0.5.0"
