[package]
name = "word_filter"
version = "0.1.0"
authors = ["ander"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
str_overlap = "0.1.1"
